// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vectordb_rpc.proto

#include "vectordb_rpc.pb.h"
#include "vectordb_rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vectordb_rpc {

static const char* VectorDB_method_names[] = {
  "/vectordb_rpc.VectorDB/Ping",
};

std::unique_ptr< VectorDB::Stub> VectorDB::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VectorDB::Stub> stub(new VectorDB::Stub(channel));
  return stub;
}

VectorDB::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Ping_(VectorDB_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VectorDB::Stub::Ping(::grpc::ClientContext* context, const ::vectordb_rpc::PingRequest& request, ::vectordb_rpc::PingReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void VectorDB::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::vectordb_rpc::PingRequest* request, ::vectordb_rpc::PingReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void VectorDB::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vectordb_rpc::PingReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void VectorDB::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::vectordb_rpc::PingRequest* request, ::vectordb_rpc::PingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

void VectorDB::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vectordb_rpc::PingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vectordb_rpc::PingReply>* VectorDB::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::vectordb_rpc::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vectordb_rpc::PingReply>::Create(channel_.get(), cq, rpcmethod_Ping_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::vectordb_rpc::PingReply>* VectorDB::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::vectordb_rpc::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::vectordb_rpc::PingReply>::Create(channel_.get(), cq, rpcmethod_Ping_, context, request, false);
}

VectorDB::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorDB_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorDB::Service, ::vectordb_rpc::PingRequest, ::vectordb_rpc::PingReply>(
          std::mem_fn(&VectorDB::Service::Ping), this)));
}

VectorDB::Service::~Service() {
}

::grpc::Status VectorDB::Service::Ping(::grpc::ServerContext* context, const ::vectordb_rpc::PingRequest* request, ::vectordb_rpc::PingReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vectordb_rpc

